import type { EntityConfig, StatusTone, ViewKey } from '../types'

export const entityConfigs: Record<ViewKey, EntityConfig> = {
  dashboard: {
    key: 'dashboard',
    title: 'Resumen',
    subtitle: 'Indicadores calculados con la informacion entregada por el backend.',
    endpoint: '',
    columns: [],
    fields: [],
  },
  users: {
    key: 'users',
    title: 'Usuarios',
    subtitle: 'Registro institucional, seguridad, rol, reputacion y estado.',
    endpoint: '/api/users',
    createEndpoint: '/api/auth/register',
    columns: [
      'id',
      'correo_institucional',
      'nombre',
      'carrera',
      'foto_url',
      'telefono',
      'zona_barrio',
      'rol',
      'reputacion_promedio',
      'total_viajes',
      'estado',
      'created_at',
    ],
    fields: [
      { key: 'correo_institucional', label: 'Correo institucional' },
      { key: 'password', label: 'Contrasena' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'carrera', label: 'Carrera' },
      { key: 'foto_url', label: 'Foto URL' },
      { key: 'telefono', label: 'Telefono' },
      { key: 'zona_barrio', label: 'Zona o barrio' },
      { key: 'estado', label: 'Estado', kind: 'select', options: ['activo', 'suspendido', 'advertido'] },
    ],
  },
  trips: {
    key: 'trips',
    title: 'Viajes',
    subtitle: 'Publicacion de rutas, cupos, reglas y estado del viaje.',
    endpoint: '/api/trips',
    columns: [
      'id',
      'conductor_id',
      'origen_zona',
      'destino_zona',
      'fecha_hora',
      'cupos_disponibles',
      'notas_reglas',
      'estado',
      'created_at',
    ],
    fields: [
      { key: 'origen_zona', label: 'Origen zona' },
      { key: 'destino_zona', label: 'Destino zona' },
      { key: 'fecha_hora', label: 'Fecha y hora', kind: 'datetime-local' },
      { key: 'cupos_disponibles', label: 'Cupos disponibles', kind: 'number' },
      { key: 'notas_reglas', label: 'Notas y reglas', kind: 'textarea' },
    ],
  },
  requests: {
    key: 'requests',
    title: 'Solicitudes',
    subtitle: 'Solicitudes de cupo realizadas por pasajeros.',
    endpoint: '/api/requests',
    columns: ['id', 'viaje_id', 'pasajero_id', 'estado', 'fecha_solicitud'],
    fields: [
      { key: 'viaje_id', label: 'Viaje', kind: 'select', relation: 'trips' },
      { key: 'pasajero_id', label: 'Pasajero', kind: 'select', relation: 'users' },
    ],
  },
  ratings: {
    key: 'ratings',
    title: 'Calificaciones',
    subtitle: 'Evaluaciones entre usuarios despues de un viaje.',
    endpoint: '/api/ratings',
    columns: ['id', 'viaje_id', 'calificador_id', 'calificado_id', 'puntuacion', 'comentario', 'created_at'],
    fields: [
      { key: 'viaje_id', label: 'Viaje', kind: 'select', relation: 'trips' },
      { key: 'calificado_id', label: 'Calificado', kind: 'select', relation: 'users' },
      { key: 'puntuacion', label: 'Puntuacion', kind: 'number' },
      { key: 'comentario', label: 'Comentario', kind: 'textarea' },
    ],
  },
  reports: {
    key: 'reports',
    title: 'Reportes',
    subtitle: 'Incidentes reportados, evidencia, estado y accion tomada.',
    endpoint: '/api/reports',
    columns: [
      'id',
      'reportante_id',
      'reportado_id',
      'viaje_id',
      'motivo',
      'evidencia_url',
      'estado',
      'accion_tomada',
      'created_at',
    ],
    fields: [
      { key: 'reportante_id', label: 'Reportante', kind: 'select', relation: 'users' },
      { key: 'reportado_id', label: 'Reportado', kind: 'select', relation: 'users' },
      { key: 'viaje_id', label: 'Viaje', kind: 'select', relation: 'trips' },
      { key: 'motivo', label: 'Motivo', kind: 'textarea' },
      { key: 'evidencia_url', label: 'Evidencia URL' },
      { key: 'estado', label: 'Estado', kind: 'select', options: ['pendiente', 'revisado', 'resuelto'] },
      { key: 'accion_tomada', label: 'Accion tomada', kind: 'textarea' },
    ],
  },
  audit_logs: {
    key: 'audit_logs',
    title: 'Auditoria',
    subtitle: 'Trazabilidad de acciones importantes dentro del sistema.',
    endpoint: '/api/audit_logs',
    columns: ['id', 'usuario_id', 'accion', 'detalles', 'fecha_hora'],
    fields: [
      { key: 'usuario_id', label: 'Usuario', kind: 'select', relation: 'users' },
      { key: 'accion', label: 'Accion' },
      { key: 'detalles', label: 'Detalles', kind: 'textarea' },
      { key: 'fecha_hora', label: 'Fecha y hora', kind: 'datetime-local' },
    ],
  },
  profile: {
    key: 'profile',
    title: 'Mi Perfil',
    subtitle: 'Informacion del usuario actual.',
    endpoint: '/api/profile',
    columns: [
      'id',
      'correo_institucional',
      'nombre',
      'carrera',
      'foto_url',
      'telefono',
      'zona_barrio',
      'rol',
      'reputacion_promedio',
      'total_viajes',
      'estado',
    ],
    fields: [
      { key: 'correo_institucional', label: 'Correo institucional' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'carrera', label: 'Carrera' },
      { key: 'foto_url', label: 'Foto URL' },
      { key: 'telefono', label: 'Telefono' },
      { key: 'zona_barrio', label: 'Zona o barrio' },
      { key: 'rol', label: 'Rol', kind: 'select', options: ['estudiante', 'admin'] },
      { key: 'reputacion_promedio', label: 'Reputacion promedio', kind: 'number' },
      { key: 'total_viajes', label: 'Total viajes', kind: 'number' },
      { key: 'estado', label: 'Estado', kind: 'select', options: ['activo', 'suspendido', 'advertido'] },
    ],
  },
}

export const viewLabels: Record<ViewKey, string> = {
  dashboard: 'Resumen',
  users: 'Usuarios',
  trips: 'Viajes',
  requests: 'Solicitudes',
  ratings: 'Calificaciones',
  reports: 'Reportes',
  audit_logs: 'Auditoria',
  profile: 'Mi Perfil',
}

export const statusTone: Record<string, StatusTone> = {
  activo: 'ok',
  estudiante: 'ok',
  admin: 'info',
  publicado: 'ok',
  abierto: 'ok',
  aceptada: 'ok',
  finalizado: 'ok',
  resuelto: 'ok',
  revisado: 'info',
  advertido: 'warning',
  completo: 'info',
  pendiente: 'warning',
  'en revision': 'info',
  'en curso': 'info',
  suspendido: 'danger',
  rechazada: 'danger',
  cancelada: 'danger',
  cancelado: 'danger',
}

export const managedViews: ViewKey[] = ['users', 'trips', 'requests', 'ratings', 'reports', 'audit_logs']

export const initialEntityState = {
  rows: [],
  loading: true,
  error: '',
}
